version: "3.7"

services:
  server:
    image: caioruizz/ruiz-ubuntu-server:1.1.2
    network_mode: host
    restart: unless-stopped
    environment:
      SSH_USER: ubuntu
      SSH_PASSWORD: umbrel
      SSH_PORT: "2222"
      WEB_PORT: "4000"
